[tool.poetry]
name = "identity-backend"
version = "0.1.0"
description = ""
authors = ["cxzlw <wsc_zds@qq.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">= 3.9"
fastapi = "^0.115.2"
pyjwt = "^2.9.0"
sqlalchemy = "^2.0.36"
aiosqlite = "^0.20.0"
argon2-cffi = "^23.1.0"
black = "^24.10.0"
uvicorn = "^0.32.0"
python-multipart = "^0.0.12"
pydantic-settings = "^2.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
