"""init

Revision ID: 3b7b3ed4c18b
Revises: d3d2441ef2ce
Create Date: 2025-05-26 18:36:40.031787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7b3ed4c18b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=256), nullable=False),
    sa.Column('redirect_uri', sa.String(length=256), nullable=False),
    sa.Column('access_token', sa.String(length=32), nullable=False),
    sa.Column('id_token', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('oauth_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=30), nullable=False),
    sa.Column('app_desc', sa.String(length=256), nullable=False),
    sa.Column('app_icon_url', sa.String(length=96), nullable=True),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('client_secret', sa.String(length=32), nullable=False),
    sa.Column('redirect_uri', sa.String(length=256), nullable=False),
    sa.Column('allowed_scopes', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('can_login', sa.Boolean(), nullable=False),
    sa.Column('shadow_banned', sa.Boolean(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('avatar_url', sa.String(length=96), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('oauth_apps')
    op.drop_table('codes')
    # ### end Alembic commands ###
