"""add app_icon_url

Revision ID: dda0d6b769d6
Revises: d3d2441ef2ce
Create Date: 2024-10-24 21:41:33.455478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda0d6b769d6'
down_revision: Union[str, None] = 'd3d2441ef2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_icon_url', sa.String(length=96), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_apps', schema=None) as batch_op:
        batch_op.drop_column('app_icon_url')

    # ### end Alembic commands ###
